#-------------------------------
# Site Settings
title: Data Meerkat
logo: # You can add own logo. For example "/images/logo.png".
description: Blog not just about Power BI


#-------------------------------
# Author Global Settings
author:
  author__name: Štěpán Rešl
  author__bio: Don't say something cannot be done, or someone who doesn't know will come and do it. In Power BI this works twice.
  author__avatar: /images/01-1.jpg


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Pages'
      submenu:
      - title: 'Authors'
        url: '/authors/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: HERO SETTINGS !!!!! CHANGE IT


#-------------------------------
# Blog Settings
blog:
  blog__title: Blog & Resources
  blog__description: Find out how to set up a successful blog or how to make yours even better!


#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Recommended
  tag__name: Motivation


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp__identifier: identifier !! NEEDS TO BE CHANGED # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Get interesting news
  mailchimp__description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp__input__text: Your Email Address...
  mailchimp__button__text: Subscribe
  mailchimp__background__image: "/images/110.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Authors'
      url: '/authors/'
    - title: 'Elements'
      url: '/elements/'


# Social Links
social:
- {icon: "ion-logo-twitter", color: "#55acee", name: Twitter, link: "https://twitter.com/tpnRel1"}
- {icon: "ion-logo-linkedin", color: "#0B66C2",name: LinkedIn,link: "https://www.linkedin.com/in/%C5%A1t%C4%9Bp%C3%A1n-re%C5%A1l-464084152/"}
- {icon: "ion-logo-mastodon", color: "#615FF9", name: Mastodon, link: "https://techhub.social/@StepanResl"}

# Example of adding a new link to the footer - {icon: "ion-logo-youtube", color: "#ff0000", name: Youtube, link: "https://youtube.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: reslstepan@outlook.cz # Add your email for contant form

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus__identifier: Štěpán the Meerkat # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id